name: Build and deploy search bar

on:
  push:
    tags:
      - 'search-bar-v*'

jobs:
  call_build:
    uses: ./.github/workflows/build_i18n.yml
    with:
      build_script: build-search-bar-only
      cloud_region: US

  call_build_for_eu:
    uses: ./.github/workflows/build_i18n.yml
    with:
      build_script: build-search-bar-only
      cloud_region: EU

  merge_multiple_us_artifacts:
    uses: ./.github/workflows/merge_upload_multiple_artifacts.yml
    needs:
      - call_build
    with:
      cloud_region: US

  merge_multiple_eu_artifacts:
    uses: ./.github/workflows/merge_upload_multiple_artifacts.yml
    needs:
      - call_build_for_eu
    with:
      cloud_region: EU

  call_acceptance_search_bar:
    uses: ./.github/workflows/acceptance_search_bar.yml
    needs: 
      - merge_multiple_us_artifacts
      - merge_multiple_eu_artifacts

  call_misc_tests:
    uses: ./.github/workflows/miscellaneous_tests.yml

  call_extract_versions:
    uses: ./.github/workflows/extract_versions.yml
    with:
      ignore_prefix: search-bar-

  call_should_deploy_major_version:
    uses: ./.github/workflows/should_deploy_major_version.yml
    with:
      ignore_prefix: search-bar-

  call_deploy_full_version:
    needs:
      - call_acceptance_search_bar
      - call_extract_versions
      - call_misc_tests
    uses: ./.github/workflows/deploy_hold.yml
    with:
      bucket: answers-search-bar
      directory: ${{ needs.call_extract_versions.outputs.full_version }}
      cache-control: 'max-age=31536000'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

  call_deploy_major_version:
    needs:
      - call_build_for_eu
      - call_acceptance_search_bar
      - call_extract_versions
      - call_misc_tests
      - call_should_deploy_major_version
    if: ${{ needs.call_should_deploy_major_version.outputs.should_deploy_major_version }}
    uses: ./.github/workflows/deploy_hold.yml
    with:
      bucket: answers-search-bar
      directory: ${{ needs.call_extract_versions.outputs.major_version }}
      cache-control: 'max-age=43200'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

  call_deploy_minor_version:
    needs:
      - call_build_for_eu
      - call_acceptance_search_bar
      - call_extract_versions
      - call_misc_tests
    uses: ./.github/workflows/deploy_hold.yml
    with:
      bucket: answers-search-bar
      directory: ${{ needs.call_extract_versions.outputs.minor_version }}
      cache-control: 'max-age=43200'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

concurrency:
  group: ci-build-and-deploy-search-bars-${{ github.ref }}-1
  cancel-in-progress: true
