name: test echo

on:
  workflow_call:
    inputs:
      environment:
        required: false
        type: string
        default: staging

jobs:
  call_test:
    # environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ secrets.SECRET_TEST }}