name: Extract versions

on:
  workflow_call:
    inputs:
      ignore_prefix:
        required: false
        default: ''
        type: string
    outputs:
      major_version:
        value: ${{ jobs.extract_versions.outputs.major_version }}
      minor_version:
        value: ${{ jobs.extract_versions.outputs.minor_version }}
      full_version:
        value: ${{ jobs.extract_versions.outputs.full_version }}

jobs:
  extract_versions:
    runs-on: ubuntu-latest
    outputs:
      minor_version: ${{ steps.vars.outputs.minor_version }}
      major_version: ${{ steps.vars.outputs.major_version }}
      full_version: ${{ steps.vars.outputs.full_version }}
    steps:
      - name: extract major and minor version substrings
        id: vars
        run: |
          MAJOR_VERSION="$(echo "${GITHUB_REF_NAME##"$IGNORE_PREFIX"}" | cut -d '.' -f 1)"
          echo "Major version: $MAJOR_VERSION"
          echo major_version=${MAJOR_VERSION} >> $GITHUB_OUTPUT
          MINOR_VERSION="$(echo "${GITHUB_REF_NAME##"$IGNORE_PREFIX"}" | cut -d '.' -f 1,2)"  
          echo "Minor version: $MINOR_VERSION"
          echo minor_version=${MINOR_VERSION} >> $GITHUB_OUTPUT
          FULL_VERSION="${GITHUB_REF_NAME##"$IGNORE_PREFIX"}"
          echo "Full version: $FULL_VERSION"
          echo full_version=${FULL_VERSION} >> $GITHUB_OUTPUT
        env:
          IGNORE_PREFIX: ${{ inputs.ignore_prefix }}}
