name: Percy Snapshots

on: 
  push:
    branches-ignore: dev/*
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 15.x
    - run: npm ci
    - run: npm run build
    - name: Percy Snapshots
      run: npx percy exec -- node tests/acceptance/percy/snapshots.mjs
      env:
        PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}