name: Percy Snapshots

on: 
  push:
    branches-ignore: dev/*
  pull_request:

jobs:
  call_percy_snapshots:
    uses: yext/slapshot-reusable-workflows/.github/workflows/percy_snapshots.yml@v1
    with:
      snapshots_script_path: tests/acceptance/percy/snapshots.js
      fetch_depth: 0
    secrets:
      PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
