name: Percy Snapshots

on: 
  push:
    branches-ignore: dev/*
  pull_request:

jobs:
  call_percy_snapshots:
    uses: yext/answers-headless/.github/workflows/percy_snapshots_reuse.yml@dev/test-reusable-workflows
    with:
      snapshots_script_path: tests/acceptance/percy/snapshots.js
    secrets:
      PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}