name: Percy Snapshots

on: 
  push:
    branches-ignore: dev/*
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build
    - run: npm i @babel/core@7.14 @babel/node@7.14
    - name: Percy Snapshots
      run: npx percy exec -- npx babel-node tests/acceptance/percy/snapshots.js --plugins @babel/plugin-transform-runtime
      env:
        PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}