name: User-Agent Acceptance Tests

on: 
  push:
    branches-ignore: dev/*
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: 15.x
    - run: npm ci
    - run: npm run build
    - run: npx testcafe --list-browsers
    - uses: DevExpress/testcafe-action@latest
      with:
        skip-install: true
        args: "\"chrome:headless,firefox:headless,safari,edge\" tests/acceptance/useragent/useragentsuite.js --config-file ./.circleci/testcafe.json"

