name: WCAG tests

on:
  pull_request:
    branches: [develop, hotfix/*, release/*, support/*]

jobs:
  call_wcag_test:
    uses: yext/slapshot-reusable-workflows/.github/workflows/wcag_test.yml@v1
    with:
      fetch_depth: 0
